title: ANNA KOSLER
logo: /assets/img/logo.png
description: Czech-born, Scandinavian-raised, Scotland-based
journalist, social psychologist, and barista
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal